# Main playbook

---
- name: Setup macOS environment
  hosts: localhost
  connection: local
  become: false  # No need for sudo unless changing system settings

  roles:
    - macos-prereqs
    - homebrew
    - dot-files
    - config-files
    - macos-defaults
    - neovim
    - fonts
