---
- name: Check if Homebrew is installed
  stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check

- name: Install Homebrew
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /opt/homebrew/bin/brew
  when: not homebrew_check.stat.exists

- name: Add Homebrew to PATH (for Apple Silicon)
  lineinfile:
    path: ~/.zshrc
    line: 'eval "$(/opt/homebrew/bin/brew shellenv)"'
    create: yes
  when: not homebrew_check.stat.exists

- name: Install Brew packages (CLI tools)
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - neovim
    - tmux
    - fzf
    - ripgrep
    - zsh
    - git
    - jq

- name: Install Brew casks (GUI applications)
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
    - google-chrome
    - visual-studio-code
    - iterm2
    - alfred
    - slack
    - rectangle
