---
- name: Check if Homebrew is installed
  stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check

- name: Install Homebrew
  command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /opt/homebrew/bin/brew
  when: not homebrew_check.stat.exists
  become: yes

- name: Add Homebrew to PATH (for Apple Silicon)
  lineinfile:
    path: ~/.zshrc
    line: 'eval "$(/opt/homebrew/bin/brew shellenv)"'
    create: yes
  when: not homebrew_check.stat.exists

- name: Install Brew packages (CLI tools)
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - 1password
    - awscli
    - btop
    - composer
    - dbeaver-community
    - dive
    - doggo
    - doggo
    - fzf
    - gawk
    - gh
    - git
    - gsed
    - hashicorp/tap/vault
    - helm
    - htop
    - ijq
    - jq
    - jq
    - k9s
    - kubecolor
    - kubectx
    - kubent
    - kubernetes-cli 
    - lsd
    - microsoft-remote-desktop
    - windows-app
    - neovim
    - node
    - php
    - ripgrep
    - starship
    - stern
    - tailspin
    - telnet
    - tldr
    - tmux
    - tokei
    - tree
    - trippy
    - trivy
    - txn2/tap/kubefwd
    - watch
    - yq
    - zsh
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - zsh-vi-mode

- name: Install Brew casks (GUI applications)
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
    - caffeine
    - docker
    - font-jetbrains-mono-nerd-font
    - google-chrome
    - iterm2
    - lens
    - maccy
    - meld
    - microsoft-office
    - microsoft-teams
    - raycast
    - rectangle
    - scroll-reverser
    - shottr
    - slack
    - visual-studio-code
    - vlc
    - wezterm
    - zed
    - zoom
